version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ivan.privalov.89@mail.ru
      PGADMIN_DEFAULT_PASSWORD: ivan064012
    ports:
      - "5050:80"

  app:
    build: ./
    container_name: java-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
#    volumes:
#      - ./target/libraryProject-0.0.1-SNAPSHOT.jar:/app.jar


volumes:
  postgres_data: